import Tesseract from "tesseract.js";

export class OcrService {
  /**
   * Extracts text from an image (JPG, PNG) using Optical Character Recognition.
   * @param buffer - The image file buffer.
   * @returns The text found inside the image.
   */
  async extractText(buffer: Buffer): Promise<string> {
    try {
      // We use Tesseract.js to recognize text.
      // 'eng' uses the English language model.
      // We disable the logger to prevent progress bars from cluttering the server console.
      const { data } = await Tesseract.recognize(buffer, "eng", {
        logger: () => {},
      });

      // Clean up the text (remove extra whitespace generated by OCR)
      const cleanedText = data.text
        .replace(/\s+/g, " ")
        .replace(/\n\s*\n/g, "\n")
        .trim();

      // Basic check to see if the image actually had text
      if (!cleanedText || cleanedText.length === 0) {
        throw new Error("No readable text found in the image.");
      }

      return cleanedText;
    } catch (error) {
      // Log the real error server-side
      console.error("OCR Service Error:", error);

      // Return a safe error message to the client
      if (error instanceof Error) {
        throw new Error(`Image text extraction failed: ${error.message}`);
      }
      throw new Error("Image text extraction failed: Unknown error");
    }
  }
}

// Export a singleton instance
export const ocrService = new OcrService();
